---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb-dev
  name: myweb-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb-dev
  template:
    metadata:
      labels:
        app: myweb-dev
    spec:
      containers:
      - image: 192.168.56.1:5001/justme/myweb:8
        imagePullPolicy: Always
        name: myweb-dev

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb-dev
  name: myweb-dev
spec:
  ports:
  - nodePort: 32224
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb-dev
  type: NodePort
